### PR TITLE
Add Docker support for local development and testing (#6)

### LINKED ISSUE #6: Docker Image
Is there a possibility to create a docker image?

Thanks.

### PR DESCRIPTION
**Pull request by Itz-Agasta**
Closes #6

This PR adds Docker support to the project for consistent local development and testing environments.

### Changes Made:
- Added Dockerfile for containerization
- Added .dockerignore file to optimize build process
- Configured production-ready Node.js Alpine image
- Set up serve package to handle static file serving

### Docker Setup Details:
- Base image: node:18-alpine
- Production dependencies only
- Serves built static files on port 3000
- Optimized for small image size

### Local Testing Steps:
```bash
# Build image
docker build -t MobinurRahaman/ellipto-iptv .

# Run container
docker run -d --name ellipto-iptv-container -p 3000:3000 MobinurRahaman/ellipto-iptv
```

Please let me know if you want to change or add anything to the PR. Also, I will be glad to add the Docker documentation to `README.md.` Just raise the issue and assign me.

Cheers 🥂
Have a great day!

### CODE REVIEW

**Comment by MobinurRahaman** [comment]
Hi @Itz-Agasta,

Thanks for your contribution to Ellipto IPTV! The Docker support you're adding looks great. However, I’d like to request a couple of changes to the image and container naming conventions to align with the project’s naming structure:

- **Image Name**: Please update the image name to `MobinurRahaman/ellipto-iptv` to match the project’s namespace (e.g., Docker Hub or other registries). This ensures consistency and avoids any potential name conflicts in the future.
- **Container Name**: Please update the container name to `ellipto-iptv-container`. This will keep it short, meaningful, and aligned with the project name.

**Updated instructions**:

```bash
# Build image
docker build -t MobinurRahaman/ellipto-iptv .

# Run container
docker run -d --name ellipto-iptv-container -p 3000:3000 MobinurRahaman/ellipto-iptv

**Comment by MobinurRahaman** [comment]
@Itz-Agasta Add Docker documentation to README.md too.

**Comment by Itz-Agasta** [comment]
Hi @MobinurRahaman, I've made the requested changes in the image and container name. I've also added the Docker documentation to the `README.md.`

Please feel free to review it when you have time. Thanks!

**Comment by MobinurRahaman** [comment]
@Itz-Agasta Thank you so much for your contribution! 🎉 Your work is a valuable addition to the project, and I really appreciate the time and effort you’ve put into this. I’ve merged your PR, and I’m excited to keep evolving on this.

I’d love to continue working together as we keep improving and adding new features to the project. Please feel free to open more PRs if you have ideas, bug fixes, or enhancements in the future – your contributions are always welcome!

Thanks again for helping make this project better! 🙏

**Pull request merged**
